CREATE TABLE [dbo].[InspectionForms] (
    [Id]                            INT             IDENTITY (1, 1) NOT NULL,
    [ApplicationId]                 INT             NOT NULL,
    [PlantManagerName]              NVARCHAR (MAX)  NULL,
    [FireFightingFacilities]        NVARCHAR (MAX)  NULL,
    [PowerSource]                   NVARCHAR (MAX)  NULL,
    [AirCompressor]                 NVARCHAR (MAX)  NULL,
    [FirstAidBox]                   NVARCHAR (MAX)  NULL,
    [AdequateHouseKeeping]          NVARCHAR (MAX)  NULL,
    [ProvisionOfWater]              NVARCHAR (MAX)  NULL,
    [MechanicalLeakTester]          NVARCHAR (MAX)  NULL,
    [GasDetector]                   NVARCHAR (MAX)  NULL,
    [MaintenanceFacilities]         NVARCHAR (MAX)  NULL,
    [AdequateSafetyFacilities]      NVARCHAR (MAX)  NULL,
    [ProtectiveWears]               NVARCHAR (MAX)  NULL,
    [SecurityCheckList]             NVARCHAR (MAX)  NULL,
    [EarthingProtectiveDevices]     NVARCHAR (MAX)  NULL,
    [EmergencyShutDownSystem]       NVARCHAR (MAX)  NULL,
    [PerimeterFence]                NVARCHAR (MAX)  NULL,
    [TrainingForOperators]          NVARCHAR (MAX)  NULL,
    [SupervisorComment]             NVARCHAR (MAX)  NULL,
    [LicenseType]                   NVARCHAR (MAX)  NULL,
    [ApplicationType]               INT             NOT NULL,
    [InspectionBy]                  NVARCHAR (MAX)  NULL,
    [DistanceToPublicBuilding]      NVARCHAR (MAX)  NULL,
    [ProximityToAccessRoad]         NVARCHAR (MAX)  NULL,
    [ProximityToAdjourningFeatures] NVARCHAR (MAX)  NULL,
    [SizeOfLand]                    NVARCHAR (MAX)  NULL,
    [HighTensionRightofWay]         NVARCHAR (MAX)  NULL,
    [AccessibilityToSite]           NVARCHAR (MAX)  NULL,
    [InspectorComment]              NVARCHAR (MAX)  NULL,
    [AnnualCngcompression]          NVARCHAR (MAX)  NULL,
    [PipeLineRightofWays]           NVARCHAR (MAX)  NULL,
    [NbrLoadingPoint]               NVARCHAR (MAX)  NULL,
    [UploadedImage]                 NVARCHAR (MAX)  NULL,
    [Longitude]                     NVARCHAR (MAX)  NULL,
    [Latitude]                      NVARCHAR (MAX)  NULL,
    [ThirdPartyContactNamePhoneNo]  NVARCHAR (MAX)  NULL,
    [ThirdPartyCompanyName]         NVARCHAR (MAX)  NULL,
    [StorageCapacity]               DECIMAL (18, 2) NULL,
    CONSTRAINT [PK_InspectionForms] PRIMARY KEY CLUSTERED ([Id] ASC)
);

